- name: add ESXi host to vcenter
  hosts: all
  gather_facts: False
  become: false
  vars:
    datacenter: cloud
    folder: /cloud/host/testhost

  tasks:
    - name: add ESXi Host to vCenter under a specific folder
      community.vmware.vmware_host:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter_name: "{{ datacenter }}"
        folder: "{{ folder }}"
        esxi_hostname: '{{ ansible_host }}'
        esxi_username: root
        esxi_password: '{{ ansible_password }}'
        state: present
        add_connected: True
      ignore_errors: true
      delegate_to: localhost

    - name: mount NFS datastore to ESXi
      community.vmware.vmware_host_datastore:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter_name: '{{ datacenter }}'
        datastore_name: '{{ item.name }}'
        datastore_type: '{{ item.type }}'
        nfs_server: '{{ item.server }}'
        nfs_path: '{{ item.path }}'
        nfs_ro: true
        esxi_hostname: '{{ ansible_host }}'
        state: present
      delegate_to: localhost
      loop:
        - { 'name': 'NasDS_vol01', 'server': '192.168.1.103', 'path': '/mnt/vault/work/install', 'type': 'nfs'}

    - name: exit maintenance mode
      community.vmware.vmware_maintenancemode:
        hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        esxi_hostname: '{{ ansible_host }}'
        timeout: 3600
        state: absent
      ignore_errors: true
      delegate_to: localhost