---

sso_password: "{{ lookup('env', 'VMWARE_PASSWORD')|default('') }}"
sso_site_name: Default-Site
sso_domain_name: home.ad

network_mount_dir: /mnt/net
vcsa_iso: iso/VMware-VCSA-all-7.0.1-17491101.iso

iso_mount_dir: /mnt/iso

network_ip_scheme: static
disk_mode: thin

vcenter_appliance_name: vcenter
vcenter_appliance_size: small

target_esx_datastore: datastore1
target_esx_portgroup: Management

ssh_enable: true
time_tools_sync: false
net_addr_family: ipv4

vcenter_ip_address: "{{ lookup('env', 'VMWARE_HOST')|default('') }}"
vcenter_username: "{{ lookup('env', 'VMWARE_USER')|default('') }}"
vcenter_password: "{{ lookup('env', 'VMWARE_PASSWORD')|default('') }}"
vcenter_fqdn: "vcenter{{ vcenter_ip_address.split('.')[-1] }}.{{ sso_domain_name }}"
vcenter_netmask: 255.255.255.0
vcenter_gateway: 192.168.1.254
vcenter_net_prefix: 24

dns_servers:
  - 8.8.4.4
ntp_servers:
  - pool.ntp.org