---

- name: gather information about vms and templates
  community.vmware.vmware_vm_info:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
  delegate_to: localhost
  register: vm_facts

- block:
    - include_tasks: mount_nfs.yml

    - include_tasks: deploy.yml
      loop: "{{ non_http_link_ova_files }}"
      when: item | basename | replace('.ova','') | replace('-ovf','') not in vm_facts.virtual_machines | list

  always:
    - include_tasks: unmount_nfs.yml
  when:
    - non_http_link_ova_files is defined
    - non_http_link_ova_files | length

- block:
    - debug:
        msg: "{{ http_link_ova_files }}"

    - include_tasks: http_upload_setup.yml

    - include_tasks: deploy_pull_mode.yml
      loop: "{{ http_link_ova_files }}"
      when: item | basename | replace('.ova','') | replace('-ovf','') not in vm_facts.virtual_machines | list
  when:
    - http_link_ova_files is defined
    - http_link_ova_files | length
