---

#- name: obtain thumbprint
#  command: openssl x509 -in /etc/vmware/ssl/rui.crt -fingerprint -sha1 -noout
#  register: esxi_ssl_thumbprint

- name: add ESXi Host to vCenter under a specific folder
  community.vmware.vmware_host:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter_name: "{{ vcenter_datacenter }}"
    cluster_name: "{{ vcenter_cluster }}"
    esxi_hostname: "{{ ansible_host }}"
    esxi_username: root
    esxi_password: "{{ ansible_password | default(ansible_ssh_password) }}"
    #esxi_ssl_thumbprint: "{{ esxi_ssl_thumbprint.stdout | replace('SHA1 Fingerprint=','') }}"
    fetch_ssl_thumbprint: true
    state: present
    add_connected: True
  delegate_to: localhost

- name: wait for vca to show up in vcenter inventory
  community.vmware.vmware_vm_info:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    vm_type: vm
  delegate_to: localhost
  register: vm_facts
  until: (vm_facts.virtual_machines | default([]) | selectattr('guest_name', 'equalto', vcenter_appliance_name) | list) | length > 0
  retries: 10
  delay: 3
  ignore_errors: yes

- name: move vcenter vm to infra resource pool
  community.vmware.vmware_guest:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    name: "{{ vcenter_appliance_name }}"
    resource_pool: infra
  delegate_to: localhost
  register: move_vcenter_vm
  until: move_vcenter_vm is success
  retries: 30
  delay: 5
  ignore_errors: yes

- name: auto-start vcenter vm
  community.vmware.vmware_host_auto_start:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    esxi_hostname: "{{ ansible_host }}"
    name: "{{ vcenter_appliance_name }}"
    power_info:
      start_action: powerOn
      start_delay: 10
      start_order: 1
      stop_action: powerOff
      wait_for_heartbeat: yes
  delegate_to: localhost

- name: ensure iso directory exists on the datastore
  community.vmware.vsphere_file module:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    datastore: '{{ target_esx_datastore }}'
    path: iso
    state: directory
  delegate_to: localhost