---

- name: ensure datacenter exists
  community.vmware.vmware_datacenter:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter_name: '{{ vcenter_datacenter }}'
    state: present

- name: ensure cluster exists
  community.vmware.vmware_cluster:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter_name: '{{ vcenter_datacenter }}'
    cluster_name: '{{ vcenter_cluster }}'
    state: present

- name: ensure drs is enabled on the cluster
  community.vmware.vmware_cluster_drs:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter_name: '{{ vcenter_datacenter }}'
    cluster_name: '{{ vcenter_cluster }}'
    enable: "{{ enable_drs }}"

- name: ensure vsan is enabled on the cluster
  community.vmware.vmware_cluster_vsan:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter_name: '{{ vcenter_datacenter }}'
    cluster_name: '{{ vcenter_cluster }}'
    enable: "{{ enable_vsan }}"
  when: enable_vsan

- name: ensure resource pools exist
  community.vmware.vmware_resource_pool:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    resource_pool: '{{ item }}'
    state: present
  loop: "{{ vcenter_resource_pools }}"

- name: ensure folders exist
  community.vmware.vcenter_folder:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter: '{{ vcenter_datacenter }}'
    folder_name: "{{ item }}"
    folder_type: vm
    state: present
  loop: "{{ vcenter_vm_folders }}"

- name: add a new vCenter license
  community.vmware.vcenter_license:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    license: "{{ vcenter_license }}"
    validate_certs: false
    state: present
  ignore_errors: true
  when: (vcenter_license|length | default(0)) > 0
