---

- name: ensure datacenter exists
  community.vmware.vmware_datacenter:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter_name: '{{ vcenter_datacenter }}'
    state: present
  delegate_to: localhost

- name: ensure cluster exists
  community.vmware.vmware_cluster:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter_name: '{{ vcenter_datacenter }}'
    cluster_name: '{{ vcenter_cluster }}'
    enable_drs: '{{ enable_drs }}'
    enable_vsan: '{{ enable_vsan }}'
    state: present
  delegate_to: localhost

- name: ensure resource pools exist
  community.vmware.vmware_resource_pool:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    cluster: '{{ vcenter_cluster }}'
    resource_pool: '{{ item }}'
    state: present
  delegate_to: localhost
  loop: "{{ vcenter_resource_pools }}"

- name: ensure folders exist
  community.vmware.vcenter_folder:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    datacenter: '{{ vcenter_datacenter }}'
    folder_name: "{{ item }}"
    folder_type: vm
    state: present
  delegate_to: localhost
  loop: "{{ vcenter_vm_folders }}"

- name: add a new vCenter license
  community.vmware.vcenter_license:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: no
    license: "{{ vcenter_license }}"
    state: present
  delegate_to: localhost
  when: (vcenter_license|length | default(0)) > 0