---

- name: find ova file
  ansible.builtin.find:
    paths: '{{ iso_mount_dir }}/vcsa'
    patterns: '*.ova'
  register: ova_file

- name: deploy appliance
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ ansible_hostname }}"
    username: "{{ ansible_user | default(ansible_ssh_user) | default('root') }}"
    password: "{{ ansible_password | default(ansible_ssh_password) }}"
    ovf: '{{ ova_file.files[0] }}'
    wait_for_ip_address: true
    validate_certs: false
    name: '{{ vcenter_appliance_name }}'
    networks: '{"Network 1": "{{ target_esx_portgroup }}"}'
    datastore: '{{ target_esx_datastore }}'
    disk_provisioning: '{{ disk_mode }}'
    deployment_option: '{{ vcenter_appliance_size }}'
    properties:
      guestinfo.cis.appliance.root.shell: /bin/bash
      guestinfo.cis.deployment.autoconfig: True
      guestinfo.cis.silentinstall: False
      guestinfo.cis.vmdir.domain-name: "{{ sso_domain_name }}"
      guestinfo.cis.vmdir.site-name: "{{ sso_site_name }}"
      guestinfo.cis.vmdir.username: "{{ vcenter_username }}"
      guestinfo.cis.vmdir.password: "{{ sso_password }}"
      guestinfo.cis.appliance.net.addr.family: "{{ net_addr_family }}"
      guestinfo.cis.appliance.root.passwd: "{{ vcenter_password }}"
      guestinfo.cis.appliance.ssh.enabled: "{{ ssh_enable }}"
      guestinfo.cis.vmdir.first-instance: True
      guestinfo.cis.ceip_enabled: True
      guestinfo.cis.appliance.ntp.servers: '{% for item in ntp_servers %}{{ item }}{{ "," if not loop.last else "" }}{% endfor %}'
      guestinfo.cis.appliance.net.pnid: "{{ vcenter_fqdn }}"
      guestinfo.cis.appliance.net.mode: "{{ network_ip_scheme }}"
      guestinfo.cis.appliance.net.addr: "{{ vcenter_ip_address | ansible.utils.ipaddr }}"
      guestinfo.cis.appliance.net.prefix: "{{ vcenter_net_prefix }}"
      guestinfo.cis.appliance.net.gateway: "{{ vcenter_gateway | ansible.utils.ipaddr }}"
      guestinfo.cis.appliance.net.dns.servers: '{% for item in dns_servers %}{{ item }}{{ "," if not loop.last else "" }}{% endfor %}'
  when:
    - ova_file is success
    - ova_file.matched is defined
    - ova_file.matched | int > 0
    - ova_file.files is defined