---

- name: ensure the iso file is unmounted
  ansible.posix.mount:
    path: '{{ iso_mount_dir }}'
    state: unmounted

- name: ensure the mount directory doesn't exist
  ansible.builtin.file:
    path: '{{ iso_mount_dir }}'
    state: absent