---

- block:
    - name: gather information about vms and templates
      vmware_vm_info:
        hostname: "{{ ansible_host }}"
        username: root
        password: "{{ ansible_password | default(ansible_ssh_password) }}"
        validate_certs: no
      delegate_to: localhost
      register: vm_facts
  rescue:
    - name: set vm_facts
      set_fact:
        vm_facts: {"virtual_machines": {}}
      when: ansible_version.full is version('2.8.0', '<')

    - name: set vm_facts
      set_fact:
        vm_facts: {"virtual_machines": []}
      when: ansible_version.full is version('2.8.0', '>=')

- block:

    - block:
        - include_tasks: mount_nfs.yml
        - include_tasks: deploy.yml
        - include_tasks: unmount_nfs.yml
      when: vcenter_ova_file is not match('^https?://')

    # for ESXI 8.0, ovftool doesn't run on the host, you can specify http(s) link for the ova file
    - include_tasks: deploy_pull_mode.yml
      when: vcenter_ova_file is match('^https?://')

    - include_tasks: wait.yml

  when:
    - (ansible_version.full is version('2.8.0', '<') and vcenter_appliance_name not in vm_facts.virtual_machines | list) or (ansible_version.full is version('2.8.0', '>=') and vcenter_appliance_name not in (vm_facts.virtual_machines | map(attribute='guest_name') | list))